services:
  - type: web
    name: medirush-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: medirush-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/user

databases:
  - name: medirush-db
    databaseName: medirush
    user: medirush_user
    plan: free